version: "3.3"

services:

  app-hello-jenkins:
    container_name: 'app-hello-jenkins'
    image: 'app-hello-jenkins'
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        - app-demo
    restart: 'unless-stopped'
    ports:
      - 7005:7005
    networks:
      app-network:
        aliases:
          - app.hello.jenkins.com

  app-hello-jenkins-test:
    container_name: 'app-hello-jenkins-test'
    image: localhost:14441/novopayment/tools/ci/postman-builder:1.0.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./postman-test/app-test:/app-test
    working_dir: /app-test
    tty: true
    stdin_open: true
    command: tail -F anything
    # command: sh /app-test/run-postman.sh
    # command: 'sh -c ls -la .'
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
    depends_on:
      - app-hello-jenkins
    networks:
      app-network:
        aliases:
          - app.hello.jenkins.test.com

networks:
  app-network:
    driver: bridge
